a=int(input('Numarul de oua pe care o da prima gaina timp de o zi='))
b=int(input('Numarul de oua pe care o da a doua gaina timp de o zi='))
c=int(input('Numarul de oua pe care o da a treia gaina timp de o zi='))
d=int(input('Numarul de oua pe care o da a patra gaina timp de o zi='))
print('Timp de o saptamana s-au obtinut',(a+b+c+d)*7,'oua')
